---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:1.11.2
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  image: rancher/dapper:1.11.2
  commands:
  - cp -r ./bin/* ./package/
  when:
    refs:
      include:
      - "refs/heads/master"
    event:
    - tag

- name: publish-image
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile
    repo: rancher/log-aggregator
    tag: ${DRONE_TAG}
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    refs:
      include:
      - "refs/heads/master"
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
